import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Google Clone Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>TEST 123</h1>
    </div>
  );
}
